### ISSUE TITLE
Top Donor is actually most recent donor

### ISSUE THREAD

**Issue by OldGrama** [OldGrama/VanillaHub#10]
**Describe the bug**
top donor on both websites shows the most recent donation, not the top donator

**To Reproduce**
go to websites

**Expected behavior**
person who has spent the most on the server should be listed

**Screenshots**
https://imgur.com/a/JGhHK5e

**Comment by jnx-02** [comment]
It was showing Top Donor of the day. 
Ive now changed it to Top Monthly Donor
