### ISSUE TITLE
Test Dummy Bug -  Throwing Trident at Test Dummy causes it to delete

### ISSUE THREAD

**Issue by jnx-02** [OldGrama/VanillaHub#12]
**Describe the bug**
Throwing Trident at Test Dummy causes the trident to disapear

(Didnt know this plugin was added or what plugin it is, so I'll see what you think)

**To Reproduce**
Steps to reproduce the behaviour:
1. Get Trident and enchant with Loyalty 3
2. Throw at a test dummy and it gone

**VanillaPod Issue**

**Comment by sxphirus** [comment]
this plugin was intended for testing 
its not officially a part of our server's "experience" so i will not be looking into this any further
