### ISSUE TITLE
Compass Loadstone Paring

### ISSUE THREAD

**Issue by FlowRate** [OldGrama/VanillaHub#2]
**Describe the bug**

-Syncing a compass to a loadstone with your main hand will not work, it has been discovered that you can sync it with your offhand. 

**To Reproduce**

1. Grab compass and loadstone
2. Place loadstone and right click with compass on mainhand
3. right click with compass on offhand

**Expected behavior**

- It was expected that you would be able to sync a compass to a loadstone using your main hand.

**Screenshots**

https://imgur.com/a/VLgtqFd

**Minecraft Version (as well as any clients or mods you use such as badlion or fabric loader)**

- 1.16.3 and Fabric Loader

**Additional context**

-May just wind up being where you can just forever use your offhand to sync, not too major of an issue.

**Comment by OldGrama** [comment]
First thought would be to change the item world edit uses for this teleportation.

Does it give you any errors such as missing permissions?

**Comment by FlowRate** [comment]
The report has been updated with a link to what it says

**Comment by OldGrama** [comment]
after looking at the image it is definitely ASyncWorldEdit fighting with us, I will see if this is something we can change. This is the unfortunate downside to plugins having dependencies on in game items to execute commands, as there are only so many items we can change it to.

**Comment by OldGrama** [comment]
Is this an issue players themselves have or is it just you? This might be due to your permission set.

**Comment by FlowRate** [comment]
It's across all players, I don't think my permissions include anything with WE.

**Comment by OldGrama** [comment]
We can change the nav wand from a compass, this is located in the plugins/WorldEdit/sessions/ folder. I do not have the permissions to do this myself.

**Comment by sxphirus** [comment]
AWE
