### ISSUE TITLE
VanillaCloud players cannot build in shop plots

### ISSUE THREAD

**Issue by OldGrama** [OldGrama/VanillaHub#6]
**Describe the bug**
people who have rented shops on vanillacloud do not have permission to build in their plot regions

**To Reproduce**
1. rent plot as normal user
2. try to build in rented plot

**Expected behavior**
Users should be able to build in the specified plot after using /as rent <plot>

**Screenshots**
n/a

**Minecraft Version (as well as any clients or mods you use such as badlion or fabric loader)**
n/a

**Additional context**
this bug so far has 2 confirmed affected players, NotParch and LuisTrollPT (both iron)

**Comment by sxphirus** [comment]
Fixed, issue was due to unexpected characters in a formatting.
