### ISSUE TITLE
Discord market channels 

### ISSUE THREAD

**Issue by FlowRate** [OldGrama/VanillaHub#7]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
-With shop additions players need multiple ways to market their items

2**Describe the solution you'd like**
-In addition to the signs at warp shop. A discord channel dedicated to player marketing would help users who have shops more difficult to find

**Additional context**
Add any other context or screenshots about the feature request here, such as links to plugins

**Comment by OldGrama** [comment]
added text channels to respective servers
