### ISSUE TITLE
Checkpoints plugin was forcing everyone on server to spawn at /warp shops everytime they died (Disabled Plugin)

### ISSUE THREAD

**Issue by jnx-02** [OldGrama/VanillaHub#8]
**Describe the bug**
Checkpoints Plugin which was added today was forcing everyone to spawn at /warp shops as it was set in the cfg. Anytime someone died they would spawn at /warp shops.

Disabled it for now as its **01.40 am** but looked through the config and there isn't an option to not have a world spawn. So could not disable the feature of the plugin. 
Disabled it fully for now until we can find a different way of doing it with this plugin or using another plugin.

**Minecraft Version (as well as any clients or mods you use such as badlion or fabric loader)**
1.16.3

**Comment by sxphirus** [comment]
@JWSchmidt1 
look what you've done

**Comment by sxphirus** [comment]
@jnx-02 has requested a new version of this plugin from the dev
